### ISSUE TITLE
Cannot load Stable Diffusion on local host 7860 

### ISSUE THREAD

**Issue by maxtoulouse31** [carlgira/oci-generative-ai#1]
Error message:

 stable-diffusion.service - systemd service start stable-diffusion
     Loaded: loaded (/etc/systemd/system/stable-diffusion.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-04-07 20:35:38 UTC; 8s ago
    Process: 32926 ExecStart=/bin/bash /home/ubuntu/stable-diffusion-webui/webui.sh (code=exited, status=1/FAILURE)
   Main PID: 32926 (code=exited, status=1/FAILURE)
        CPU: 46.297s

Apr 07 20:35:37 generative-ai bash[32931]:   File "/home/ubuntu/stable-diffusion-webui/launch.py", line 251, in start
Apr 07 20:35:37 generative-ai bash[32931]:     webui.webui()
Apr 07 20:35:37 generative-ai bash[32931]:   File "/home/ubuntu/stable-diffusion-webui/webui.py", line 173, in webui
Apr 07 20:35:37 generative-ai bash[32931]:     app.add_middleware(GZipMiddleware, minimum_size=1000)
Apr 07 20:35:37 generative-ai bash[32931]:   File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/appli>
Apr 07 20:35:37 generative-ai bash[32931]:     raise RuntimeError("Cannot add middleware after an application has started")
Apr 07 20:35:37 generative-ai bash[32931]: RuntimeError: Cannot add middleware after an application has started
Apr 07 20:35:38 generative-ai systemd[1]: stable-diffusion.service: Main process exited, code=exited, status=1/FAILURE
Apr 07 20:35:38 generative-ai systemd[1]: stable-diffusion.service: Failed with result 'exit-code'.
Apr 07 20:35:38 generative-ai systemd[1]: stable-diffusion.service: Consumed 46.297s CPU time.
~
~
~
~
~
~
~
~
~
~
~

**Comment by carlgira** [comment]
Hi, 
I just fixed and update the code. 

- Change the image to an Oracle Linux with CUDA (saving some time).
- Change the GPU to A10.
- Update some dependencies that were giving problems.

Thanks

**Comment by maxtoulouse31** [comment]
Thank you - however, still cannot connect on port 7860. Is it maybe because Hugging Face no longer requires accepting terms for Stable Diffusion model? Terminal outputting: "channel 8: open failed: connect failed: Connection refused
channel 7: open failed: connect failed: Connection refused"

After 1h15 of trying to fine tune Stable Diffusion on Dream Booth, I get error message: "client_loop: send disconnect: Broken pipe"

Bloom and Dream Booth UI's working. 

Bloom inference runs.

**Comment by maxtoulouse31** [comment]
Thank you - however, still cannot connect on port 7860. Is it maybe because Hugging Face no longer requires accepting terms for Stable Diffusion model? Terminal outputting: "channel 8: open failed: connect failed: Connection refused
channel 7: open failed: connect failed: Connection refused"

After 1h15 of trying to fine tune Stable Diffusion on Dream Booth, I get error message: "client_loop: send disconnect: Broken pipe"

Bloom and Dream Booth UI's working.

Bloom inference runs.

**Comment by maxtoulouse31** [comment]
Command systemctl status stable-diffusion (typo in Troubleshooting main page, two b's in stable)

Outputs 

Apr 09 15:28:45 generative-ai bash[28573]:   File "/home/ubuntu/stable-diffusion-webui/launch.py", line 251, in start
Apr 09 15:28:45 generative-ai bash[28573]:     webui.webui()
Apr 09 15:28:45 generative-ai bash[28573]:   File "/home/ubuntu/stable-diffusion-webui/webui.py", line 173, in webui
Apr 09 15:28:45 generative-ai bash[28573]:     app.add_middleware(GZipMiddleware, minimum_size=1000)
Apr 09 15:28:45 generative-ai bash[28573]:   File "/home/ubuntu/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/ap>
Apr 09 15:28:45 generative-ai bash[28573]:     raise RuntimeError("Cannot add middleware after an application has started")
Apr 09 15:28:45 generative-ai bash[28573]: RuntimeError: Cannot add middleware after an application has started
Apr 09 15:28:46 generative-ai systemd[1]: stable-diffusion.service: Main process exited, code=exited, status=1/FAILURE
Apr 09 15:28:46 generative-ai systemd[1]: stable-diffusion.service: Failed with result 'exit-code'.
Apr 09 15:28:46 generative-ai systemd[1]: stable-diffusion.service: Consumed 47.828s CPU time.
